application: dospadel
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /src
  static_dir: src

- url: /
  script: dospadel.app

- url: /new_product
  script: dospadel.app
  login: admin

- url: /product/img
  script: dospadel.app

- url: /product/(.*?)
  script: dospadel.app

- url: /reserves
  script: dospadel.app
  login: required

- url: /reserves/(.*?)
  script: dospadel.app
  login: required

- url: /upload
  script: dospadel.app
  login: admin

- url: /transactions
  script: dospadel.app

- url: /check
  script: dospadel.app

- url: /products
  script: dospadel.app

- url: /admin
  script: dospadel.app
  login: admin

libraries:
- name: jinja2
  version: latest